repos:
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        language_version: python3.10
        args: ["--line-length=88"]
        exclude: "migrations/"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.2.5
    hooks:
      - id: prettier
        additional_dependencies: ["prettier"]
        files: ^frontend/.*\.(js|jsx|ts|tsx|css|scss|html)$
