services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    expose:
      - "${BACKEND_PORT}"
    volumes:
      - ./backups:/app/backups

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    expose:
      - "${FRONTEND_PORT}"
    environment:
      - VITE_API_SERVER=${VITE_API_SERVER}

  nginx:
    image: nginx:alpine
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

  memcached:
    image: memcached:alpine
    restart: always
    expose:
      - "${MEMCACHED_PORT}"

volumes:
  postgres_data:
