# Generated by Django 5.2.1 on 2025-05-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.CharField(default='Three', max_length=20),
            preserve_default=False,
        ),
    ]
